test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# We use Hetzner object storage in production
hetzner:
  service: S3
  endpoint: https://fsn1.your-objectstorage.com
  access_key_id: <%= ENV["HETZNER_ACCESS_KEY"] %>
  secret_access_key: <%= ENV["HETZNER_SECRET_KEY"] %>
  region: fsn1 # Falkenstein
  bucket: <%= ENV["HETZNER_BUCKET"] %>
